trigger:

  - main

pool: practice-am

variables:

  imageName: 'asmitamore/nodeapp:latest'

steps:

  - task: Docker@2

    displayName: Build and push an image

    inputs:

      repository: $(imageName)

      command: buildAndPush

      Dockerfile: dockerfile

      containerRegistry: dockerhub

  - task: CopyFiles@2

    displayName: 'Copy manifest file'

    inputs:

      SourceFolder: '$(Build.SourcesDirectory)'

      Contents: 'deploymentservice.yml'  # Specify the name of your manifest file

      TargetFolder: '$(Pipeline.Workspace)'  

  - task: KubernetesManifest@0

    displayName: 'Deploy to Kubernetes'

    inputs:

      action: deploy

      kubernetesServiceConnection: 'kube-am'

      manifests: |

        $(Pipeline.Workspace)/deploymentservice.yml
